import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#6e4ea1',
        'on-primary':                 '#ffffff',
        'primary-container':          '#c3a0fa',
        'on-primary-container':       '#523183',
        'primary-fixed':              '#ecdcff',
        'primary-fixed-dim':          '#d6baff',
        'on-primary-fixed':           '#280057',
        'on-primary-fixed-variant':   '#553587',
        'surface-tint':               '#6e4ea1',
        'inverse-primary':            '#d6baff',
        'secondary':                  '#84504c',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#ffbbb5',
        'on-secondary-container':     '#7b4844',
        'secondary-fixed':            '#ffdad6',
        'secondary-fixed-dim':        '#f9b6b0',
        'on-secondary-fixed':         '#34100e',
        'on-secondary-fixed-variant': '#693a36',
        'tertiary':                   '#5e5e5e',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#b0b0b0',
        'on-tertiary-container':      '#434343',
        'tertiary-fixed':             '#e2e2e2',
        'tertiary-fixed-dim':         '#c6c6c6',
        'on-tertiary-fixed':          '#1b1b1b',
        'on-tertiary-fixed-variant':  '#474747',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'background':                 '#fdf9ee',
        'on-background':              '#1c1c15',
        'surface':                    '#fdf9ee',
        'on-surface':                 '#1c1c15',
        'surface-variant':            '#e6e2d7',
        'on-surface-variant':         '#4a4550',
        'surface-bright':             '#fdf9ee',
        'surface-dim':                '#dddacf',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f7f3e8',
        'surface-container':          '#f2eee3',
        'surface-container-high':     '#ece8dd',
        'surface-container-highest':  '#e6e2d7',
        'inverse-surface':            '#323129',
        'inverse-on-surface':         '#f5f0e5',
        'outline':                    '#7b7481',
        'outline-variant':            '#ccc3d2',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
      spacing: {
        'gutter':         '24px',
        'margin-desktop': '64px',
        'margin-mobile':  '24px',
        'stack-gap':      '16px',
        'section-gap':    '120px',
      },
      fontFamily: {
        'headline-xl':        ['"Playfair Display"', 'serif'],
        'headline-lg':        ['"Playfair Display"', 'serif'],
        'headline-lg-mobile': ['"Playfair Display"', 'serif'],
        'label-md':           ['"JetBrains Mono"', 'monospace'],
        'label-sm':           ['"JetBrains Mono"', 'monospace'],
        'body-lg':            ['"Hanken Grotesk"', 'sans-serif'],
        'body-md':            ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'headline-xl':        ['80px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':        ['48px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['36px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-md':           ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-sm':           ['12px', { lineHeight: '1.4', letterSpacing: '0.1em',  fontWeight: '500' }],
        'body-lg':            ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
      boxShadow: {
        'warm-glow': '0 4px 16px rgba(110,78,161,0.04), 0 16px 32px rgba(0,0,0,0.04)',
      },
      keyframes: {
        pulse: {
          '0%':   { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(34,197,94,0.7)' },
          '70%':  { transform: 'scale(1)',    boxShadow: '0 0 0 6px rgba(34,197,94,0)' },
          '100%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(34,197,94,0)' },
        },
      },
      animation: {
        'pulse-dot': 'pulse 2s infinite',
      },
    },
  },
  plugins: [],
}

export default config
